### PR TITLE
Fixed focus state when input has error and toggle placeholder on focus

### PR DESCRIPTION
**Pull request by agliga**
PLEASE SQUASH AND MERGE

When focusing on input label, we should show the floating label as non error, but when blurring it should go back to error if `aria-invalid` is set.
Unfocused
Screen Shot 2020-11-09 at 10 41 02 AM
Focused with aria-invalid
Screen Shot 2020-11-09 at 10 41 06 AM

When placeholder is present, then will remove it and only show it on focus
Screen Shot 2020-11-10 at 10 14 22 AM
Screen Shot 2020-11-10 at 10 14 31 AM

### CODE REVIEW

**Review by ianmcburnie — COMMENTED** [review]
Does the demo page need updating to show value in red when invalid too? Currently it is black.

Screen Shot 2020-11-10 at 12 48 17 PM

**Review by ianmcburnie — COMMENTED** [review]
Can your mutation observer also detect when value is updated or cleared? If so, we could automatically call the refresh method on those events, and avoid needing to do it manually in following state:

Screen Shot 2020-11-10 at 1 48 46 PM

**Comment by agliga** [comment]
> Can your mutation observer also detect when value is updated or cleared? If so, we could automatically call the refresh method on those events, and avoid needing to do it manually in following state:
> 
> Screen Shot 2020-11-10 at 1 48 46 PM

Unfortunatly, we cannot trigger on value change in the dom:
https://stackoverflow.com/questions/32383349/detect-value-change-in-input-tag-with-vanilla-javascript-and-mutationobserver

I could change it to check for value changes, however the users can call `refresh` when they change the `value`.

**Comment by agliga** [comment]
> Does the demo page need updating to show value in red when invalid too? Currently it is black.
> 
> Screen Shot 2020-11-10 at 12 48 17 PM

Done, had to move the styles around.

**Comment by ianmcburnie** [comment]
> I could change it to check for value changes, however the users can call refresh when they change the value.

Yeah, that's the way I've had it up to now. Let's keep it the same then for now and we can always add that enhancement later if we need to.

**Review by ianmcburnie — APPROVED** [review]

**Review by austingardner — APPROVED** [review]
LGTM

**Pull request merged**
